### ISSUE TITLE
Raspberry Pi running issues

### ISSUE THREAD

**Issue by bill-luu** [UCSolarCarTeam/Epsilon-Onboard-Media-Control#12]
Remind Bill to put a proper description later.

**Comment by bseto** [comment]
@bill-luu Whats the proper description lol

**Comment by bill-luu** [comment]
It was along the lines of a GStreamer error, the Ui would pop up, but attempting to play the song would just result in nothing happening. I think it might be the GStreamer version on the Pi (1.0, I think it only works on 0.1). @louisj381 is working on configuring the Pi so once that's done we can try again.
