### ISSUE TITLE
Linux Mint 18 Gstreamer issues

### ISSUE THREAD

**Issue by bill-luu** [UCSolarCarTeam/Epsilon-Onboard-Media-Control#20]
Issues when trying to get the Song Player to run on Linux mint 18. Gstreamer is missing plugins

**Comment by bill-luu** [comment]
So I looked around on my computer that also runs linux mint 18, and basically uninstalled all my gstreamer related stuff and reinstalled them. Try running these commands and see what happens:
````
sudo apt-get update
sudo apt-get install gstreamer0.10-plugins-*
sudo apt-get install libgstreamer*
````

**Comment by ExtraGravity** [comment]
How is this an issue, no problem has been posed here.

**Comment by bill-luu** [comment]
Updated the description, similar to #7, but we never said _which_ gstreamer0.10 package to download. Tried a few yesterday but they didn't work, so I think we have to install libgstreamer stuff too.

**Comment by bill-luu** [comment]
Now that we aren't using GStreamer anymore, this isn't an issue.
